### ISSUE TITLE
PreAnalysis encoding seems to be not working

### ISSUE THREAD

**Issue by rigaya** [GPUOpen-LibrariesAndSDKs/AMF#66]
I was checking for the behavior of preanalysis, but it does not seem to work.

The options I was trying for H.264 is below,

`VCEEncoderD3D.exe -output test_none.264 -WIDTH 1280 -HEIGHT 720 -FRAMES 500 -CODEC H264 -usage transcoding -RateControlMethod VBR -targetBitrate 2000000 -RateControlPreAnalysisEnable none`

`VCEEncoderD3D.exe -output test_preanalysis_1.264 -WIDTH 1280 -HEIGHT 720 -FRAMES 500 -CODEC H264 -usage transcoding -RateControlMethod VBR -targetBitrate 2000000 -RateControlPreAnalysisEnable enabled`

`VCEEncoderD3D.exe -output test_preanalysis_2.264 -WIDTH 1280 -HEIGHT 720 -FRAMES 500 -CODEC H264 -usage transcoding -RateControlMethod VBR -targetBitrate 2000000 -RateControlPreAnalysisEnable enabled2`

`VCEEncoderD3D.exe -output test_preanalysis_4.264 -WIDTH 1280 -HEIGHT 720 -FRAMES 500 -CODEC H264 -usage transcoding -RateControlMethod VBR -targetBitrate 2000000 -RateControlPreAnalysisEnable enabled4`

However, all 4 files was exactly the same.

Then for HEVC,

`VCEEncoderD3D.exe -output test.hevc -WIDTH 1280 -HEIGHT 720 -FRAMES 500 -CODEC HEVC -HevcUsage transcoding -HevcRateControlPreAnalysisEnable false`

`VCEEncoderD3D.exe -output test_prepass.hevc -WIDTH 1280 -HEIGHT 720 -FRAMES 500 -CODEC HEVC -HevcUsage transcoding -HevcRateControlPreAnalysisEnable true`

Again, I got exactly the same files.

How can I make preanalysis work, or is it not supported yet?

**Comment by MikhailAMD** [comment]
VCEEncoderD3D sample uses synthetic image that is very easy to compress. Pre-analysis algorithm cannot find additional improvements for compressing. Please try TraanscodeHW sample with real video.

**Comment by Xaymar** [comment]
You can see the effects slightly if you turn the bitrate really low (64kbit for example). However as Mikhail said, there is not much room for improvement, the sample image is just too simple.

**Comment by rigaya** [comment]
Thank you very much Mikhail and Xaymar, for your comments.

As you have suggested, I tried with TranscodeHW, and sample videos from [here](http://www.sample-videos.com/) (mp4, 30MB sample, 720p, 25fps, 170sec), using options below.

`TranscodeHW.exe -input SampleVideo_1280x720_30mb.mp4 -output test_disabled.264 -CODEC H264 -Usage transcoding -QualityPreset balanced -RateControlMethod vbr -TargetBitrate 200000 -MinQP 0 -MaxQP 51 -IDRPeriod 300 -RateControlPreanalysisEnable disabled`
`TranscodeHW.exe -input SampleVideo_1280x720_30mb.mp4 -output test_enabled.264  -CODEC H264 -Usage transcoding -QualityPreset balanced -RateControlMethod vbr -TargetBitrate 200000 -MinQP 0 -MaxQP 51 -IDRPeriod 300 -RateControlPreanalysisEnable enabled`

However, the two files are exactly the same, which means all bytes are the same. I have also checked with other qualitypresets, or other usage options.

GPU used is as below on Win10 x64, Radeon Driver 17.1.1 environment.
DX9 : Chosen Device 0: Device ID: 67EF [Radeon(TM) RX 460 Graphics]

Is this expected, or do I lack some additional options?

**Comment by Xaymar** [comment]
I think you are correct, it doesn't have any effect. There does not even seem to be an encoding speed impact when it is supposedly enabled. I think this is a problem in the sample applications though, or something introduced with 17.1.1.
In the OBS plugin I have had the RateControlPreAnalysis option for a while, except I used it as a boolean. It did some wonders for the output quality there, so is 17.1.1 missing the necessary VCE firmware update for AMF 1.4?

**Comment by rigaya** [comment]
Hmm, I see...

Yes, as Xaymar says, I also cannot find speed impact when I switch on pre-analysis at my environment, it's almost the same speed whether the options is on or off.

**Comment by Xaymar** [comment]
So I did some further testing. While Pre-Analysis literally doesn't do anything on AVC, it has a significant impact on HEVC (approx 7% slower) - this means that the AVC pre-pass is either not working or has not ever made it into a driver.

**Comment by Xaymar** [comment]
More testing revealed that the PSNR and SSIM values are perfectly identical with AVC/H264 and are minimally better (0.00010) with HEVC when Pre-Analysis is enabled. I'm running driver 17.1.2 now, so there is definitely something missing in HW

**Comment by Xaymar** [comment]
Results on 17.3.1:

![soffice bin_2017-03-12_16-54-10](https://cloud.githubusercontent.com/assets/437395/23833408/4af00ea4-0745-11e7-9f1a-4053093c5e61.png)

Still only working on HEVC footage, no idea why. I went through every possible driver reinstall route and even manually cleaned and PreAnalysis still does nothing for AVC. :(

**Comment by rigaya** [comment]
Thank you for the information. I've also tested 17.3.1, and it still seems to do nothing...

**Comment by Xaymar** [comment]
This is still not working on 17.4.1.

**Comment by Xaymar** [comment]
17.5.1 report: This and VBAQ still do nothing. Also discovered a strange quality issue, see #87.

**Comment by Xaymar** [comment]
I've re-run my tests and noticed that with 17.5.2 installed, PreAnalysis was actually doing something when used together with VBR instead of CBR. VBAQ is still not doing anything, so unsure if that parameter is even useful. 

![image](https://cloud.githubusercontent.com/assets/437395/26469330/e875af4c-4199-11e7-9b9a-7715057e5cdb.png)

As you can see in the above image, VBR with PreAnalysis has slightly worse statistical quality and this is also true when viewing the file itself (there's a lot more blocky-ness). What you can't see there is that the bitrate distribution is completely different:

![image](https://cloud.githubusercontent.com/assets/437395/26469518/8edc32d4-419a-11e7-85cb-a3567c9afdd3.png)
![image](https://cloud.githubusercontent.com/assets/437395/26469534/9fb75552-419a-11e7-9b58-465dc1bc6af2.png)

The first one is bitrate without PreAnalysis, the second one is with it. Both didn't reach the target average of 3500kbit, but one has a lower peak bitrate which in theory is better. So I'd say that PreAnalysis does not improve quality, but is able to keep the bitrate average better.

**Comment by MikhailAMD** [comment]
Pre-analysis should be fixed in 17.7.2 driver.

**Comment by Xaymar** [comment]
Seems to be implemented, though I don't know if it actually does something. Footage with and without Pre-Pass looks almost identical, only added VBAQ made it worse (VBAQ introduces heavy blockyness now).

**Comment by MSxDOS** [comment]
7 months later, not only it's not fixed, but now VBAQ is also broken? I'm speechless...

**Comment by Xaymar** [comment]
> 7 months later, not only it's not fixed, but now VBAQ is also broken? I'm speechless...

It's implemented, don't know where you got the "not fixed" from. Nothing is broken here, the effects on the footage are just different and almost impossible to tell apart by a human eye.

**Comment by MSxDOS** [comment]
PrePass was significantly improving the quality before 17.1.1, now the difference is "almost impossible to tell apart by a human eye". I could just call it useless, but since it worked very well with 16.x.x I say it's broken.

**Comment by Xaymar** [comment]
Pre Pass was not implemented before 17.7.2

**Comment by Benman2785** [comment]
PrePass has a noticeable effect on quality - if Webcam added the video wont be that blocky anymore ;)

https://www.youtube.com/watch?v=eOV8uP-6hnw
vs
TO BE UPLOADED SOON

**Comment by MikhailAMD** [comment]
Pre-pass is content-specific. Could we close this issue or there are more to be explored?

**Comment by MikhailAMD** [comment]
Closed as no response provided.
