### ISSUE TITLE
H264: AMF_VIDEO_ENCODER_PICTURE_TYPE_SKIP results in messed up encoded data

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#84]
With driver 17.4.4 (and probably all previous ones) setting AMF_VIDEO_ENCODER_FORCE_PICTURE_TYPE to AMF_VIDEO_ENCODER_PICTURE_TYPE_SKIP causes the next submission to return AMF_FAIL for an unknown reason. See the log below:

```
22:39:47.581: ==== Recording Start ===============================================
22:39:47.581: [ffmpeg muxer: 'adv_file_output'] Writing file 'D:/Projects/Video/[ToDo]/2017-04-30 22-39-47.mkv'...
22:39:47.615: [AMF] <Id: 5> EncodeStore: PTS(       0) DTS(       0) TS(               0) Duration(          166667) Type(IDR)
22:39:47.624: [AMF] <Id: 5> EncodeStore: PTS(       1) DTS(       1) TS(          166667) Duration(          166667) Type(Automatic)
22:39:47.624: [AMF] <Id: 5> EncodeLoad: PTS(       0) DTS(       0) TS(               0) Duration(          166667) Size(          113333) Type(IDR)
22:39:47.624: [AMF] <Id: 5>    Timings: Allocate(   33564 ns) Store( 9953890 ns) Convert(   13938 ns) Main( 8688997 ns) Load(   22470 ns)
22:39:47.640: [AMF] <Id: 5> EncodeStore: PTS(       2) DTS(       2) TS(          333333) Duration(          166666) Type(Automatic)
22:39:47.640: [AMF] <Id: 5> EncodeLoad: PTS(       1) DTS(       1) TS(          166667) Duration(          166667) Size(            5055) Type(P)
22:39:47.641: [AMF] <Id: 5>    Timings: Allocate(   19627 ns) Store( 1981107 ns) Convert(    7111 ns) Main(16524680 ns) Load(    1707 ns)
22:39:47.656: [AMF Runtime] [22:39:47.568][VCEEncoderTrace]  Warning: GetProperty BPicturesDeltaQP failed in AMFPropertyStorageExImpl with return code:0x3
22:39:47.656: [AMF Runtime] [22:39:47.571][VCEEncoderTrace]  Warning: GetProperty ReferenceBPicturesDeltaQP failed in AMFPropertyStorageExImpl with return code:0x3
22:39:47.657: [AMF] <Id: 5> EncodeStore: PTS(       3) DTS(       3) TS(          500000) Duration(          166667) Type(Automatic)
22:39:47.657: [AMF] <Id: 5> EncodeLoad: PTS(       2) DTS(       2) TS(          333333) Duration(          166666) Size(            5529) Type(P)
22:39:47.657: [AMF] <Id: 5>    Timings: Allocate(   24746 ns) Store( 1697523 ns) Convert(    7111 ns) Main(17097822 ns) Load(    1991 ns)
22:39:47.673: [AMF] <Id: 5> EncodeStore: PTS(       4) DTS(       4) TS(          666667) Duration(          166667) Type(Automatic)
22:39:47.674: [AMF] <Id: 5> EncodeLoad: PTS(       3) DTS(       3) TS(          500000) Duration(          166667) Size(            5616) Type(P)
22:39:47.674: [AMF] <Id: 5>    Timings: Allocate(   21333 ns) Store( 1971437 ns) Convert(    7396 ns) Main(16618545 ns) Load(    1706 ns)
22:39:47.690: [AMF] <Id: 5> EncodeStore: PTS(       5) DTS(       5) TS(          833333) Duration(          166666) Type(Skip)
22:39:47.691: [AMF] <Id: 5> EncodeLoad: PTS(       4) DTS(       4) TS(          666667) Duration(          166667) Size(            5610) Type(P)
22:39:47.691: [AMF] <Id: 5>    Timings: Allocate(   24177 ns) Store( 1658271 ns) Convert(    7111 ns) Main(17083600 ns) Load(    1706 ns)
22:39:47.707: [AMF] <Id: 5> EncodeStore: PTS(       6) DTS(       6) TS(         1000000) Duration(          166667) Type(Automatic)
22:39:47.707: [AMF] <Id: 5> [Main] Submitting Surface failed, error AMF_FAIL (code 1)
22:39:47.707: [AMF] <Plugin::Interface::H264Interface::~H264Interface> Finalizing...
22:39:47.757: [AMF Runtime] [22:39:47.707][AMFEncoderVCE]    Error: ..\..\..\..\..\runtime\src\components\EncoderVCE\EncoderVCEImpl.cpp(2313):AMF_ERROR 1 : AMF_FAIL: SubmitInput() Failed to execute Encode() = 0x80000009
22:39:47.757: [AMF Runtime] [22:39:47.707][AMFEncoderVCE]    Error: ..\..\..\..\..\runtime\src\components\EncoderVCE\EncoderVCEImpl.cpp(2443):Assertion failed:Drain() Failed to execute Encode() = 0x80000009
22:39:53.736: [AMF] <Id: 5> Finalized.
22:39:53.736: [AMF] <Plugin::Interface::H264Interface::~H264Interface> Complete.
22:39:53.736: Error encoding with encoder 'recording_h264'
22:39:53.797: [AMF Runtime] [22:39:53.725][AMFDeviceComputeImpl]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImpl.cpp(683):OpenCL failed, error = -101:clReleaseMemObject()
22:39:53.797: [AMF Runtime] [22:39:53.728][AMFDeviceComputeImpl]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImpl.cpp(683):OpenCL failed, error = -101:clReleaseMemObject()
```

As you can see above, the encoder was set to skip every 5th frame, essentially reducing FPS by 1/5th. For 60fps that would turn it into 48fps - if this actually worked. But unfortunately, Frame 5 caused Frame 6 to no longer be accepted and thus the encoder safely destructed itself so that it does not corrupt the output.

**Comment by Xaymar** [comment]
Seems like it is not only AMF_VIDEO_ENCODER_PICTURE_TYPE_SKIP causing this, forcing any other type will also cause this behaviour to appear, though a little bit later. The error is identical, so refer to the first log.

**Comment by Xaymar** [comment]
Further testing reveals the following behaviour:

* AMF_VIDEO_ENCODER_PICTURE_TYPE_IDR, AMF_VIDEO_ENCODER_PICTURE_TYPE_I, AMF_VIDEO_ENCODER_PICTURE_TYPE_P, AMF_VIDEO_ENCODER_PICTURE_TYPE_B can only be applied every 1/4th IDR Period. If it is applied more than that, SubmitInput returns AMF_FAIL.
* AMF_VIDEO_ENCODER_PICTURE_TYPE_SKIP always causes SubmitInput to return AMF_FAIL, no matter when it set.

The error is always the same, the reason it got there is not however.

**Comment by MikhailAMD** [comment]
Hi tried this using SimpleEncoder sample. I confirm the issue with SKIP - I don't see GPU crash like your log suggests but I see that the encoder stops produce output frames. IDR, I and P frames work OK for me. B-frame fails because RX 480 doesn't support B-Frames. I've opened a ticket for SKIP.
Could you please try to repro IDR, I, P using SimpleEncoder sample with following changes before encoder->SubmitInput() call:
if(submitted != 0 && (submitted % 5) == 0)
        {
            surfaceIn->SetProperty(AMF_VIDEO_ENCODER_FORCE_PICTURE_TYPE, AMF_VIDEO_ENCODER_PICTURE_TYPE_SKIP);
        }
You may need to add to the sample all properties you set to the encoder. The behavior can depend on other properties. 
Thanks,

**Comment by Oldgam3r** [comment]
> RX 480 doesn't support B-Frames.

> 
why ?

**Comment by Xaymar** [comment]
> I don't see GPU crash like your log suggests but I see that the encoder stops produce output frames.

The GPU doesn't actually crash. It's just the AMF runtime that no longer works in that instance of the loaded DLL. Simply restarting the program makes AMF work again.

> B-frame fails because RX 480 doesn't support B-Frames.

B-Frames were tested on an R9 285, please do not forget that I have more than one GPU to test on.

>  IDR, I and P frames work OK for me. Could you please try to repro IDR, I, P using SimpleEncoder sample with following changes before encoder->SubmitInput() call <code>
> You may need to add to the sample all properties you set to the encoder. The behavior can depend on other properties.

I can't reproduce this on 17.5.1 anymore, so this was likely fixed in that driver. I have updated the original issue to reflect this.

**Comment by Xaymar** [comment]
Still broken on 17.7.2

**Comment by MikhailAMD** [comment]
Yes, the ticket is open.

**Comment by Xaymar** [comment]
18.x made this worse by causing this to actually freeze the GPU in place.

**Comment by Xaymar** [comment]
* Driver: 18.7.1
* OS: Windows 10 1803 Build 17134.165

It seems that the crash and freeze problem has been fixed, but now another problem has been introduced due to that. The skipped frame seems to not have been replaced by a repeat last frame, but by actual nothing - which is being referenced by the next frame.

Here is an example video: [2018-07-21_02-31-41.zip](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/2215765/2018-07-21_02-31-41.zip)

**Comment by MikhailAMD** [comment]
We checked this stream with Vega analyzer. Skip frames look ok. Every macroblock refers to previous frame. 
On the side note : stream has double SPS/PPS NAL units in the first frame and the first SPS is incorrect.

**Comment by Xaymar** [comment]
Please look at the actual file in any recent media player (Movies & TV, VLC Media Player, MPC-HC, etc). You will see that whatever the AMD Encoder encoded was complete nonsense, adding blocks and wrong colors over the entirety of the encoded video. If you for some reason can't watch the file, here are extracted frames:

Original File:
![Original Frame](https://user-images.githubusercontent.com/437395/43104694-88124688-8ed2-11e8-9afa-932adfa3b4c9.png)

Encoded File without Skipping:
![Encoded File without Skipping](https://user-images.githubusercontent.com/437395/43105039-c8cf8cc0-8ed3-11e8-99d7-6d4b817d7bfd.png)

Encoded File with Skipping:
![VLC Media Player](https://user-images.githubusercontent.com/437395/43104280-43e5c544-8ed1-11e8-912f-8cbeeb0aee92.png)

The file with Skipping looks identical in all players (Movies & TV, VLC Media Player, MPC-HC, ffmpeg extract frames, Chrome, Firefox, Safari, Opera, Flash, ...). To me, this looks pretty damn wrong.

**Comment by MikhailAMD** [comment]
Reproduced on AMF TranscodeHW sample and logged into internal bug tracking system
Thanks

**Comment by Xaymar** [comment]
What is the status on this issue?

**Comment by MikhailAMD** [comment]
AMD developer pinged.

**Comment by MikhailAMD** [comment]
This issue should be fixed in driver.

**Comment by Xaymar** [comment]
Still happening with Radeon Driver 19.7.2 on a Radeon RX 480 and Radeon VII.

[2019-07-24 12-12-29.zip](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/3426173/2019-07-24.12-12-29.zip)

**Comment by Xaymar** [comment]
Actually on the second recording it worked as expected. It's only the first recording that does this now.

**Comment by Xaymar** [comment]
Going to close this as there has been no further activity, and I no longer have any AMD GPUs to test with.
